language: node_js
node_js:
  - "12"
notifications:
  email: false

cache:
  directories:
  - node_modules

script:
 npm install && npm run build && npm run lint && npm test
  
deploy:
  provider: pages
  github-token: $travis
  on:
    branch: master