language: node_js
node_js:
  - "stable"
notifications:
  email: false

cache:
  directories:
  - node_modules

script:
  npm run build

test_script:
  npm run lint && npm test

deploy:
  provider: pages
  github-token: $travis
  on:
    branch: master